name: NPM Auto Deprecate

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  auto-deprecate:
    name: NPM Auto Deprecate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Project
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Setup Node
        uses: josh-development/.github/setup-node@main

      - name: Deprecate Versions
        run: yarn npm-deprecate
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
