name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Add ESLint Problem Matcher
        run: echo "::add-matcher::.github/problemMatchers/eslint.json"

      - name: Setup Node & Install Dependencies
        uses: josh-development/.github/setup-node@main
        with:
          turbo: true

      - name: Run ESLint
        run: yarn lint --fix=false

  building:
    name: Compile Source Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Add TypeScript Problem Matcher
        run: echo "::add-matcher::.github/problemMatchers/tsc.json"

      - name: Setup Node & Install Dependencies
        uses: josh-development/.github/setup-node@main
        with:
          turbo: true

      - name: Build Code
        run: yarn build

  docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Node & Install Dependencies
        uses: josh-development/.github/setup-node@main
        with:
          turbo: true

      - name: Generate Documentation
        run: yarn docs

  testing:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Node & Install Dependencies
        uses: josh-development/.github/setup-node@main
        with:
          turbo: true

      - name: Run Tests
        run: yarn test --coverage

      - name: Store Code Coverage Report
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: coverage
          path: coverage/

  upload-coverage-report:
    name: Upload Code Coverage Report
    needs: [testing]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 2

      - name: Download Coverage Report
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
        with:
          name: coverage
          path: coverage/

      - name: Codecov Upload
        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7 # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage/
          fail_ci_if_error: true
