name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Setup Node
        uses: josh-development/.github/setup-node@main
        with:
          turbo: true
      - name: Add ESLint Problem Matcher
        run: echo "::add-matcher::.github/problemMatchers/eslint.json"
      - name: Run ESLint
        run: yarn lint --fix=false
      - name: Add TypeScript Problem Matcher
        run: echo "::add-matcher::.github/problemMatchers/tsc.json"
      - name: Compile Source Code
        run: yarn build --cache-dir=./.turbo
      - name: Generate Documentation
        run: yarn docs --cache-dir=./.turbo
      - name: Run Tests
        run: yarn test --coverage
      - name: Store Code Coverage Report
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4
        with:
          name: coverage
          path: coverage/

  upload-coverage-report:
    name: Upload Code Coverage Report
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 2
      - name: Download Coverage Report
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 # v4
        with:
          name: coverage
          path: coverage/
      - name: Codecov Upload
        uses: codecov/codecov-action@e0b68c6749509c5f83f984dd99a76a1c1a231044 # v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage/
          fail_ci_if_error: true
