name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
      - name: Setup Node
        uses: josh-development/.github/setup-node@main
        with:
          turbo: true
      - name: Add ESLint Problem Matcher
        run: echo "::add-matcher::.github/problemMatchers/eslint.json"
      - name: Run ESLint
        run: yarn lint --fix=false
      - name: Add TypeScript Problem Matcher
        run: echo "::add-matcher::.github/problemMatchers/tsc.json"
      - name: Compile Source Code
        run: yarn build --cache-dir=./.turbo
      - name: Generate Documentation
        run: yarn docs --cache-dir=./.turbo
      - name: Run Tests
        run: yarn test --coverage
      - name: Store Code Coverage Report
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          name: coverage
          path: coverage/

  upload-coverage-report:
    name: Upload Code Coverage Report
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 2
      - name: Download Coverage Report
        uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
        with:
          name: coverage
          path: coverage/
      - name: Codecov Upload
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage/
          fail_ci_if_error: true
